name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create or use (e.g., latest)'
        required: true
        default: 'latest'
      branch:
        description: 'Branch to checkout (e.g., master)'
        required: true
        default: 'master'

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure workspace ownership
        run: echo "chown -R $USER $GITHUB_WORKSPACE" && sudo chown -R $USER $GITHUB_WORKSPACE

      # https://github.com/actions/checkout/blob/v3/README.md
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}  # Use the secret as an environment variable
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.event.inputs.branch }}

      - name: Prepare release body
        run: |
          RELEASE_TAG=${{ github.event.inputs.tag }}
          if [[ $RELEASE_TAG == 'nightly' ]]; then
            PRERELEASE=true
          else
            PRERELEASE=false
          fi
          echo "Workflow triggered by workflow_dispatch with tag: $RELEASE_TAG"
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV
          RELEASE_DATETIME=$(date --rfc-3339=seconds)
          echo Release $RELEASE_TAG created from $GITHUB_SHA at $RELEASE_DATETIME > release_body.md

      # https://github.com/marketplace/actions/docker-login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: lmshg
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Build and push slim image linux/amd64
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: lmshg/wvp-pro:${{ env.RELEASE_TAG }}
          file: docker/wvp/Dockerfile
          build-args: |
            LIGHTEN=1
          platforms: linux/amd64